/*
    Constructors 

    Definition: A constructor is a special member function of a class that is automatically called when an object of the class is created. 
    It is used to initialize the object's data members and set up any necessary resources.

    Key Features of Constructors:
    1. Same Name as Class: A constructor must have the same name as the class it belongs to.
    2. No Return Type: Constructors do not have a return type, not even void.
    3. Automatically Called: A constructor is automatically invoked when an object is created.
    4. Can be Overloaded: A class can have multiple constructors with different parameter lists (constructor overloading).
    5. Can have Default Parameters: Constructors can have default parameters, allowing for flexible object creation.

    Types of Constructors:
    1. Default Constructor: A constructor that takes no parameters or has default values for all parameters. It is automatically generated by the compiler if no constructors are defined.
    2. Parameterized Constructor: A constructor that takes parameters to initialize the object's data members with specific values.
    3. Copy Constructor: A constructor that creates a new object as a copy of an existing object. It takes a reference to an object of the same class as a parameter.    
*/


#include <iostream>
using namespace std;

class Person
{
    public:
        string name;
        int age;
        
        // Default Constructor
        Person()
        {
            name = "Harsha";
            age = 17;
        }
        // Parameterized Constructor
        Person(string n, int a) 
        {
            name = n; //or this->name = n; 
            //name = name .This is also correct but it can lead to confusion, so using this-> 
            // is recommended to clearly indicate that we are referring to the class member variable.
            age = a;
        }
        // Copy Constructor
        Person(const Person &p)
        {
            name = p.name;
            age = p.age;
        }

        void displayInfo()
        {
            cout<<"Name: "<<name<<endl;
            cout<<"Age: "<<age<<endl;
        }
};

int main()
{
    // Creating an object of the Person class using the default constructor
    Person person1;
    // Displaying the information of person1
    person1.displayInfo();

    // Creating an object using the parameterized constructor
    Person person2("Alex", 25);  
    // Displaying the information of person2
    person2.displayInfo();

    // Creating an object using the copy constructor
    Person person3(person1); // person3 is a copy of person1
    // Displaying the information of person3
    person3.displayInfo();

    return 0;
}

// Output:
// Name: Harsha
// Age: 17
// Name: Alex
// Age: 25
// Name: Alex
// Age: 25

// Copy Constructor Example

#include <iostream>
using namespace std;

class Student
{
    public:
        int id;

        //Constructor
        Student(int i)
        {
            id = i;
        }

        // Copy Constructor
        Student(const Student &s)
        {
            id = s.id;
        }

};

int main()
{
    Student s1(101);
    Student s2(s1); // s2 is a copy of s1 or Student s2 = s1; // This also calls the copy constructor

    cout<<"ID of s1: "<<s1.id<<endl;
    cout<<"ID of s2: "<<s2.id<<endl;
    return 0;

}

// Output:
// ID of s1: 101
// ID of s2: 101